version: '3.8'

services:
  fake-be-livestream:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    
  # Uncomment below if you want to use external PostgreSQL database instead of H2
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: livestream_db
  #     POSTGRES_USER: livestream_user
  #     POSTGRES_PASSWORD: livestream_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data: